/**
 * Type definitions for GNSS data.
 *
 * ProcessingResult and nested types are auto-generated by tsify-next in
 * trajix-wasm. HeaderInfo and FixRecord are from trajix
 * (no tsify) so we define them here.
 */
export type {
  ProcessingResult,
  RecordCounts,
  FixQuality,
  StatusEpochJs,
  ConstellationStatsJs,
  FixEpochJs,
  TrajectoryPointJs,
  SensorTimeSeries,
  DecimatedSample,
  SensorXyz,
  OrientationValue,
  RotationValue,
  SatelliteSnapshot,
} from "trajix-wasm";

/** Device header info (matches trajix::parser::header::HeaderInfo). */
export interface HeaderInfo {
  version: string;
  platform: number;
  manufacturer: string;
  model: string;
  gnss_hardware: string;
}

/** Fix record (matches trajix::record::fix::FixRecord). */
export interface FixRecord {
  provider: string; // "Gps" | "Flp" | "Nlp" (serde enum)
  latitude_deg: number;
  longitude_deg: number;
  altitude_m: number | null;
  speed_mps: number | null;
  accuracy_m: number | null;
  bearing_deg: number | null;
  unix_time_ms: number;
  speed_accuracy_mps: number | null;
  bearing_accuracy_deg: number | null;
  elapsed_realtime_ns: number | null;
  vertical_accuracy_m: number | null;
  mock_location: boolean;
  num_used_signals: number | null;
  vertical_speed_accuracy_mps: number | null;
  solution_type: string | null;
}
